// generated by ChatGPT, edited by me to fix bugs

// create web audio api context
const audioCtx = new AudioContext();

// create Oscillator node
const oscillator = audioCtx.createOscillator();
oscillator.type = "square"; // square wave

// Function to schedule a note
function playNote(frequency, delay) {
    oscillator.frequency.setValueAtTime(frequency, audioCtx.currentTime);
}

// Start the oscillator
oscillator.connect(audioCtx.destination);
oscillator.start();

// Timing setup using setTimeout
const noteDuration = 400; // duration of each note in ms
const melody = [
    { frequency: 440, time: 0 },        // A4
    { frequency: 493.88, time: noteDuration / 2 }, // B4
    { frequency: 523.25, time: noteDuration }, // C5
    { frequency: 440, time: noteDuration * 1.5 }, // A4
    { frequency: 349.23, time: noteDuration * 2 }, // F4
    { frequency: 392, time: noteDuration * 2.5 }, // G4
    { frequency: 523.25, time: noteDuration * 3 }, // C5
    { frequency: 440, time: noteDuration * 3.5 }  // A4
];

// Loop through the melody array and schedule the notes
melody.forEach((note) => {
    setTimeout(() => {
        playNote(note.frequency, note.time);
    }, note.time);
});
